---
- name: Set configured SSH port fact
  ansible.builtin.set_fact:
    configured_port: "{{ ansible_port }}"
  changed_when: false
  tags:
    - openssh
    - validate

- name: Check reachability on default SSH port 22
  ansible.builtin.wait_for:
    port: 22
    state: started
    host: "{{ ansible_host | default(inventory_hostname) | default(ansible_ssh_host) }}"
    connect_timeout: 5
    timeout: 10
  delegate_to: localhost
  ignore_errors: true
  register: default_ssh
  tags:
    - openssh
    - validate

- name: Set inventory ansible_port to default when reachable
  ansible.builtin.set_fact:
    ansible_port: 22
  when:
    - default_ssh is defined
    - not default_ssh.failed
  register: ssh_port_set
  changed_when: false
  tags:
    - openssh
    - validate

- name: Check reachability on configured SSH port
  ansible.builtin.wait_for:
    port: "{{ ansible_port }}"
    state: started
    host: "{{ ansible_host | default(inventory_hostname) | default(ansible_ssh_host) }}"
    connect_timeout: 5
    timeout: 10
  delegate_to: localhost
  ignore_errors: true
  register: configured_ssh
  when:
    - default_ssh is defined
    - default_ssh.failed
  tags:
    - openssh
    - validate

- name: Confirm configured SSH port is reachable
  ansible.builtin.debug:
    msg: SSH port is configured properly
  when:
    - configured_ssh is defined
    - configured_ssh.state is defined
    - not configured_ssh.failed
  register: ssh_port_set
  changed_when: false
  tags:
    - openssh
    - validate

- name: Fail if SSH port was not auto-detected
  ansible.builtin.fail:
    msg: "The SSH port is neither 22 nor {{ ansible_port }}."
  when: ssh_port_set is undefined
  tags:
    - openssh
    - validate

- name: Gather facts after SSH port detection
  ansible.builtin.setup:
  tags:
    - openssh
    - validate
