---
- name: Preserve currently configured SSH port
  become: false
  ansible.builtin.set_fact:
    configured_port: "{{ ansible_port | default('22') }}"
  tags:
    - openssh
    - validate

- name: Check if target host is reachable on TCP port 22
  become: false
  ansible.builtin.wait_for:
    host: >-
      {{
        ansible_host
        | default(inventory_hostname)
        | default(ansible_ssh_host | default(inventory_hostname))
      }}
    port: 22
    state: started
    connect_timeout: 5
    timeout: 10
  delegate_to: localhost
  ignore_errors: true
  register: default_ssh
  tags:
    - openssh
    - validate

- name: Use TCP port 22 when it is reachable
  become: false
  ansible.builtin.set_fact:
    ansible_port: '22'
  when:
    - default_ssh is defined
    - not (default_ssh.skipped | default(false))
    - not (default_ssh.failed | default(false))
  register: ssh_port_set
  tags:
    - openssh
    - validate

- name: Check if target host is reachable on configured SSH port
  become: false
  ansible.builtin.wait_for:
    host: >-
      {{
        ansible_host
        | default(inventory_hostname)
        | default(ansible_ssh_host | default(inventory_hostname))
      }}
    port: "{{ configured_port }}"
    state: started
    connect_timeout: 5
    timeout: 10
  delegate_to: localhost
  ignore_errors: true
  register: configured_ssh
  when:
    - default_ssh is defined
    - not (default_ssh.skipped | default(false))
    - default_ssh.failed
  tags:
    - openssh
    - validate

- name: Keep configured SSH port when it is reachable
  become: false
  ansible.builtin.set_fact:
    ansible_port: "{{ configured_port }}"
  when:
    - configured_ssh is defined
    - not (configured_ssh.skipped | default(false))
    - not (configured_ssh.failed | default(false))
  register: ssh_port_set
  tags:
    - openssh
    - validate

- name: Fail when the SSH port cannot be auto-detected
  become: false
  ansible.builtin.fail:
    msg: >-
      Unable to reach {{ inventory_hostname }} on TCP port 22 or
      configured TCP port {{ configured_port }}.
  when:
    - ssh_port_set is undefined
  tags:
    - openssh
    - validate

- name: Gather deferred facts after SSH port detection
  ansible.builtin.setup:
  tags:
    - openssh
    - validate
