---
- name: Validate variables and derive OS-specific values
  ansible.builtin.import_tasks: pretasks.yml
  tags:
    - openssh
    - validate

- name: Configure OpenSSH server
  ansible.builtin.import_tasks: sshd.yml
  tags:
    - openssh
    - config
