---
- name: Converge
  hosts: all
  vars:
    openssh_port: 22
    openssh_log_level: INFO
    openssh_x11forwarding: no
    openssh_max_auth_tries: 4
    openssh_client_alive_interval: 300
    openssh_client_alive_count_max: 0
    openssh_login_grace_time: 60
    openssh_banner: /etc/issue.net
    openssh_allow_tcp_forwarding: no
    openssh_max_sessions: 4
    openssh_allow_users: ['myuser']
    openssh_allow_groups: []
    openssh_deny_users: []
    openssh_deny_groups: []
    openssh_ignore_rhosts: yes
    openssh_host_based_authentication: no
    openssh_permit_root_login: no
    openssh_permit_empty_passwords: no
    openssh_permit_user_environment: no
    openssh_use_pam: yes
    openssh_max_startups: '10:30:60'
    openssh_use_dns: yes
    openssh_macs:
      - hmac-sha2-512-etm@openssh.com
      - hmac-sha2-256-etm@openssh.com
      - hmac-sha2-512
      - hmac-sha2-256
    openssh_kex:
      - curve25519-sha256
      - curve25519-sha256@libssh.org
      - diffie-hellman-group14-sha256
      - diffie-hellman-group16-sha512
      - diffie-hellman-group18-sha512
      - ecdh-sha2-nistp521
      - ecdh-sha2-nistp384
      - ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
    openssh_ciphers:
      - chacha20-poly1305@openssh.com
      - aes256-gcm@openssh.com
      - aes128-gcm@openssh.com
      - aes256-ctr
      - aes192-ctr
      - aes128-ctr


  pre_tasks:

    - name: Update packages on debian family systems
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

  roles:
    - guidugli.openssh
