---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    openssh_port: 1234
    openssh_allow_users:
      - myuser
    openssh_allow_groups: []
    openssh_deny_users: []
    openssh_deny_groups: []
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
